### ISSUE TITLE
WSL

### ISSUE THREAD

**Issue by jpnurmi** [canonical/workshops#197]
```
2022/11/18 11:04:22.072561 cmd_run.go:1055: WARNING: cannot start document portal: dial unix /run/user/1000/bus: connect: no such file or directory

(workshops:5244): Gdk-WARNING **: 11:04:22.200: Settings portal not found: Could not connect: No such file or directory

(workshops:5244): IBUS-WARNING **: 11:04:22.255: Failed to mkdir /home/user/snap/workshops/213/.config/ibus/bus: Not a directory
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: SocketException: Connection failed (OS Error: Permission denied, errno = 13), address = /var/snap/lxd/common/lxd/unix.socket, port = 0
#0      _NativeSocket.startConnect (dart:io-patch/socket_patch.dart:682)
#1      _RawSocket.startConnect (dart:io-patch/socket_patch.dart:1827)
#2      RawSocket.startConnect (dart:io-patch/socket_patch.dart:27)
#3      Socket._startConnect (dart:io-patch/socket_patch.dart:2048)
#4      Socket.startConnect (dart:io/socket.dart:759)
#5      LxdClient._createClient.<anonymous closure> (package:lxd/src/lxd_client.dart:74)
#6      _ConnectionTarget.connect (dart:_http/http_impl.dart:2443)
#7      _HttpClient._getConnection.connect (dart:_http/http_impl.dart:2867)
#8      _HttpClient._getConnection (dart:_http/http_impl.dart:2872)
#9      _HttpClient._openUrl (dart:_http/http_impl.dart:2727)
#10     _HttpClient.openUrl (dart:_http/http_impl.dart:2591)
#11     LxdClient._requestSync (package:lxd/src/lxd_client.dart:548)
#12     LxdClient._connect (package:lxd/src/lxd_client.dart:532)
#13     LxdClient._requestSync (package:lxd/src/lxd_client.dart:545)
#14     LxdClient.getInstances (package:lxd/src/lxd_client.dart:202)
#15     _LxdService.init (package:lxd_service/src/service.dart:78)
#16     main (package:workshops/main.dart:23)
#17     _runMain.<anonymous closure> (dart:ui/hooks.dart:134)
#18     _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:297)
#19     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:192) 
```

**Comment by jpnurmi** [comment]
Works for me...
<img width="887" alt="image" src="https://user-images.githubusercontent.com/140617/202771465-d5aabd2f-cc6b-4fd4-97b7-f7599ae70398.png">
