### ISSUE TITLE
When LXD is not installed

### ISSUE THREAD

**Issue by jpnurmi** [canonical/workshops#291]
When LXD is not installed, the app should present an error screen with a nice human-readable error description together with installation instructions.

**Comment by jpnurmi** [comment]
For reference, snapcraft's error for uninitialized LXD:
```sh
$ snapcraft --verbosity verbose
Starting Snapcraft 7.2.9                                                                                                                                                                    
Logging execution to '/home/jpnurmi/.cache/snapcraft/log/snapcraft-20230103-112403.270629.log'                                                                                              
Running on amd64 for amd64                                                                                                                                                                  Traceback (most recent call last):
  File "/snap/snapcraft/8619/bin/snapcraft", line 8, in <module>
    sys.exit(run())
  File "/snap/snapcraft/8619/lib/python3.8/site-packages/snapcraft/cli.py", line 228, in run
    _run_dispatcher(dispatcher)
  File "/snap/snapcraft/8619/lib/python3.8/site-packages/snapcraft/cli.py", line 204, in _run_dispatcher
    dispatcher.run()
  File "/snap/snapcraft/8619/lib/python3.8/site-packages/craft_cli/dispatcher.py", line 448, in run
    return self._loaded_command.run(self._parsed_command_args)
  File "/snap/snapcraft/8619/lib/python3.8/site-packages/snapcraft/commands/lifecycle.py", line 259, in run
    super().run(parsed_args)
  File "/snap/snapcraft/8619/lib/python3.8/site-packages/snapcraft/commands/lifecycle.py", line 132, in run
    parts_lifecycle.run(self.name, parsed_args)
  File "/snap/snapcraft/8619/lib/python3.8/site-packages/snapcraft/parts/lifecycle.py", line 208, in run
    _run_command(
  File "/snap/snapcraft/8619/lib/python3.8/site-packages/snapcraft/parts/lifecycle.py", line 249, in _run_command
    _run_in_provider(project, command_name, parsed_args)
  File "/snap/snapcraft/8619/lib/python3.8/site-packages/snapcraft/parts/lifecycle.py", line 474, in _run_in_provider
    providers.ensure_provider_is_available(provider)
  File "/snap/snapcraft/8619/lib/python3.8/site-packages/snapcraft/providers.py", line 83, in ensure_provider_is_available
    LXDProvider.ensure_provider_is_available()
  File "/snap/snapcraft/8619/lib/python3.8/site-packages/craft_providers/lxd/lxd_provider.py", line 76, in ensure_provider_is_available
    ensure_lxd_is_ready()
  File "/snap/snapcraft/8619/lib/python3.8/site-packages/craft_providers/lxd/installer.py", line 141, in ensure_lxd_is_ready
    raise errors.LXDError(
craft_providers.lxd.errors.LXDError: LXD has not been properly initialized.
Execute 'lxd init --auto' to initialize LXD.
Visit https://linuxcontainers.org/lxd/getting-started-cli/ for instructions on installing and configuring LXD for your operating system.
```
